monitor = DP-1,preferred,auto,1
monitor = eDP-1,preferred,auto,1.25
monitor = HDMI-A-1,highres,auto,1,mirror,eDP-1
$TERMINAL = kitty;

# source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/keybind.conf

# Keyboard
input {
  kb_layout = us # XKB layout
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  force_no_accel = 1
  # kb_model = cherryblue # XKB model
  # kb_variant = dvorak # XKB variant
  # numlock_by_default = false 
  # repeat_rate = 25
  # repeat_delay = 600
  # accel_profile = flat # flat, adaptive

  touchpad {
    disable_while_typing=1
    natural_scroll=1
  }
}

general {
    gaps_in = 5
    gaps_out = 5
    border_size = 3
    col.active_border = rgba(7aa2f7ee) rgba(bb9af7ee) 45deg
    col.inactive_border = rgba(1a1b26aa)

    layout = dwindle
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = true
  vrr = 0
  animate_manual_resizes = true
  mouse_move_focuses_monitor = true
  enable_swallow = true
  swallow_regex = ^(wezterm)$
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    
    blur {
        enabled = false
        size = 2
        passes = 2
    }

  shadow {
    enabled = false
    range = 4
    render_power = 3
    color = rgba(1a1a1aee)
  }
}

#ani
animations {
  enabled = false
  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = liner, 1, 1, 1, 1

#animation  
  animation = windows, 1, 6, wind, slide
  animation = windowsIn, 1, 6, winIn, slide
  animation = windowsOut, 1, 5, winOut, slide
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, liner
  animation = borderangle, 1, 30, liner, loop
  animation = fade, 1, 10, default
  animation = workspaces, 1, 5, wind
}

dwindle {
  # no_gaps_when_only = false
  pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  preserve_split = true # you probably want this
}

# master {
#     # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
#     new_is_master = true
# }
gestures {
  workspace_swipe = on
  workspace_swipe_distance = 200
  workspace_swipe_create_new = false
  workspace_swipe_forever = true
}

xwayland {
  force_zero_scaling = true
}
